### ISSUE TITLE
zsh & pipefail

### ISSUE THREAD

**Issue by bennuru** [bcgsc/goldrush#104]
I am getting stuck at the tigmint step with the following error:
tigmint-make tigmint-long draft=w16_x10_golden_path.goldrush-edit-polished reads=long_reads cut=250 t=32 G=94000000 span=2 dist=500
zsh: no such option: pipefail
zsh: no such option: pipefail
zsh: no such option: pipefail
zsh: no such option: pipefail
make[1]: Entering directory `/.../.../.../.../goldrush'
gzip -dc  | /long-to-linked -l250 -m2000 -g94000000 | gzip > long_reads.cut250.fa.gz
zsh: no such option: pipefail
make[1]: *** [long_reads.cut250.fa.gz] Error 1
make[1]: Leaving directory `/.../.../.../.../goldrush'
make: *** [/.../.../.../.../conda/envs/goldrush/bin/goldrush.make:246: w16_x10_golden_path.goldrush-edit-polished.cut250.tigmint.fa] Error 2

**Comment by lcoombe** [comment]
Hi @bennuru,

How did you install GoldRush and Tigmint? Can you double check that you have zsh installed properly?

Thank you for your interest in GoldRush!
Lauren

**Comment by bennuru** [comment]
Hi @lcoombe 
It is a Conda environment. And 'which zsh' does give me '/usr/bin/zsh'. So I do have zsh in my env. I just commented out Line 83 of tigmint-make, and it seems to be running fine. Will update if I can get it to completion without any further hiccups.

**Comment by lcoombe** [comment]
That's strange, because `zsh` is a listed dependency in the Tigmint conda recipe (https://github.com/bioconda/bioconda-recipes/blob/master/recipes/tigmint/meta.yaml). I sometimes have seen that issue with older `zsh` versions which I have seen when using the `/usr/bin/zsh`.

What version of Tigmint is installed?
I'm also not totally sure which line you are commenting out, because I'm guessing that you aren't referring to the current line 83 in the master branch? https://github.com/bcgsc/tigmint/blob/master/bin/tigmint-make#L83  

I'd recommend running the test demo first to iron out any issues - it's fast and just helps to make you more confident in your installations. I can't guarantee that things will work as expected with commenting out lines of code :)

**Comment by bennuru** [comment]
Here is the Conda env list:
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
abyss                     2.3.5                h41cdee2_1    bioconda
arpack                    3.7.0                hdefa2d7_2    conda-forge
bcftools                  1.3.1                h5bf99c6_7    bioconda
bedtools                  2.30.0               h468198e_3    bioconda
btllib                    1.5.1            py38h4a32c8e_0    bioconda
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
curl                      7.71.1               he644dc0_3    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
glpk                      5.0                  h445213a_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
goldrush                  1.0.2            py38hfe0f59a_0    bioconda
gperftools                2.10                 h09c0d1c_0    conda-forge
gzip                      1.12                 h166bdaf_0    conda-forge
htslib                    1.3.1                h18ffd7a_3    bioconda
icu                       72.1                 hcb278e6_0    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
k8                        0.2.5                hd03093a_2    bioconda
krb5                      1.17.2               h926e7f8_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcurl                   7.71.1               hcdd3856_3    conda-forge
libdivsufsort             2.0.2                hec16e2b_6    bioconda
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libhwloc                  2.9.0                hd6dc26d_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libidn2                   2.3.4                h166bdaf_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libunwind                 1.6.2                h9c3ff4c_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxml2                   2.10.3               hfdac1af_6    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
lrzip                     0.621                h159dde0_5    bioconda
lzo                       2.10              h516909a_1000    conda-forge
make                      4.3                  hd18ef5c_1    conda-forge
metis                     5.1.0             h58526e2_1006    conda-forge
minimap2                  2.24                 h7132678_1    bioconda
mpfr                      4.2.0                hb012696_0    conda-forge
mpi                       1.0                     openmpi    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
ntlink                    1.3.8            py38hf4f3596_1    bioconda
numpy                     1.24.2           py38h10c12cc_0    conda-forge
openmpi                   4.1.5              h414af15_101    conda-forge
openssl                   1.1.1t               h0b41bf4_0    conda-forge
pandas                    2.0.0            py38hdc8b05c_0    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pigz                      2.6                  h27826a3_0    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
pybedtools                0.8.1            py38h1c8e9b9_2    bioconda
pysam                     0.9.1           py38hd1a2d5f_10    bioconda
python                    3.8.15          h257c98d_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-igraph             0.10.4           py38hd98a34f_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.8                      3_cp38    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
samtools                  1.3.1                h80b0bb3_7    bioconda
setuptools                67.6.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
suitesparse               5.10.1               h9e50725_1    conda-forge
tar                       1.34                 hb2e2bae_1    conda-forge
tbb                       2021.8.0             hf52228f_0    conda-forge
texttable                 1.6.7              pyhd8ed1ab_0    conda-forge
tigmint                   1.2.1                      py_0    bioconda
tk                        8.6.12               h27826a3_0    conda-forge
util-linux                2.36             py38h7de7a29_1    conda-forge
wget                      1.20.3               ha56f1ee_1    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zip                       3.0                  h7f98852_1    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge

So I have tigmint 1.2.1 that got installed into the Conda env.

Also the line that I commented out from (/.../.../.../.../conda/envs/goldrush/bin/tigmint-make) is:
80. SHELL=bash -e -o pipefail
81. ifneq ($(shell command -v zsh),)
82. # Set pipefail to ensure that all commands of a pipe succeed.
83. #SHELL=zsh -e -o pipefail
84. # Report run time and memory usage with zsh.

**Comment by lcoombe** [comment]
Hi @bennuru,

We're currently at Tigmint v1.2.9, so your installed version is a few releases old. You will likely have a smoother time if you update Tigmint to the newest version.

Otherwise, do try running the demo with your commented out version - it's the best way for you to make sure that your installation is working!

**Comment by bennuru** [comment]
@lcoombe 
I do not know why Conda installed the Tigmint 1.2.1. Manually installing 1.2.9 took care of the zsh problem. Thank you.

**Comment by lcoombe** [comment]
Great, I'm glad that solved the issue!

**Comment by asan-emirsaleh** [comment]
Hello dear colleagues! I have the similar issue in fresh setup of Goldrush via conda.
```
tigmint-make tigmint-long draft=w16_x10_golden_path.goldrush-edit-polished reads=lr_comb_conservative cut=250 t=32 G=1400000000 span=2 dist=500
make[1]: Entering directory '/<path>/25_ass_goldrush'
pigz -p32 -dc  | /home/emirsaleh/miniconda3/envs/goldrush2-env/bin/long-to-linked -l250 -m2000 -g1400000000 | pigz -p32 > lr_comb_conservative.cut250.fa.gz
pigz: skipping: <stdin> empty
make[1]: *** [/home/emirsaleh/miniconda3/envs/goldrush2-env/bin/tigmint-make:198: lr_comb_conservative.cut250.fa.gz] Error 1
make[1]: *** Deleting file 'lr_comb_conservative.cut250.fa.gz'
make[1]: Leaving directory '/<path>/25_ass_goldrush'
make: *** [/home/emirsaleh/miniconda3/envs/goldrush2-env/bin/goldrush.make:253: w16_x10_golden_path.goldrush-edit-polished.cut250.tigmint.fa] Error 2
```

There is an issue with Tigmint too:
```
$ conda list -n goldrush-env
# packages in environment at /home/emirsaleh/miniconda3/envs/goldrush-env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
abyss                     2.3.7                hec08913_1    bioconda
bcftools                  1.3.1                h5bf99c6_7    bioconda
bedtools                  2.31.1               hf5e1c6e_2    bioconda
btllib                    1.7.1            py38h2494328_0    bioconda
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.11.0               h470a237_1    bioconda
ca-certificates           2025.1.31            hbcca054_0    conda-forge
cairo                     1.16.0            h6cf1ce9_1008    conda-forge
curl                      7.71.1               he644dc0_8    conda-forge
expat                     2.6.4                h5888daf_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
gmp                       6.3.0                hac33072_2    conda-forge
goldrush                  1.0.3            py38h2494328_1    bioconda
gperftools                2.10                 h09c0d1c_0    conda-forge
gzip                      1.13                 hd590300_0    conda-forge
htslib                    1.3.1                h18ffd7a_3    bioconda
icu                       68.2                 h9c3ff4c_0    conda-forge
intervaltree              3.1.0              pyhd8ed1ab_1    conda-forge
k8                        1.2                  h6618dc6_1    bioconda
kernel-headers_linux-64   3.10.0              he073ed8_18    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_4    conda-forge
libasprintf               0.23.1               h8e693c7_0    conda-forge
libblas                   3.9.0           31_h59b9bed_openblas    conda-forge
libcblas                  3.9.0           31_he106b2a_openblas    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libdivsufsort             2.0.2               h7b50bb2_10    bioconda
libedit                   3.1.20250104    pl5321h7949ede_0    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.6.4                h5888daf_0    conda-forge
libffi                    3.4.6                h2dba641_0    conda-forge
libgcc                    14.2.0               h767d61c_2    conda-forge
libgcc-ng                 14.2.0               h69a702a_2    conda-forge
libgettextpo              0.23.1               h5888daf_0    conda-forge
libgfortran               14.2.0               h69a702a_2    conda-forge
libgfortran-ng            14.2.0               h69a702a_2    conda-forge
libgfortran5              14.2.0               hf1ad2bd_2    conda-forge
libglib                   2.80.2               hf974151_0    conda-forge
libgomp                   14.2.0               h767d61c_2    conda-forge
libiconv                  1.18                 h4ce23a2_1    conda-forge
libidn2                   2.3.8                ha4ef2c3_0    conda-forge
liblapack                 3.9.0           31_h7ac8fdf_openblas    conda-forge
liblzma                   5.6.4                hb9d3cd8_0    conda-forge
liblzma-devel             5.6.4                hb9d3cd8_0    conda-forge
libnghttp2                1.41.0               hab1572f_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.29          pthreads_h94d23a6_0    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx                 14.2.0               h8f9b012_2    conda-forge
libstdcxx-ng              14.2.0               h4852527_2    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libunwind                 1.6.2                h9c3ff4c_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcb                    1.17.0               h8a09558_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
lrzip                     0.651                h5753e1d_0    bioconda
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              hd590300_1001    conda-forge
make                      4.4.1                hb9d3cd8_2    conda-forge
minimap2                  2.28                 he4a0461_3    bioconda
mpi                       1.0                     openmpi    conda-forge
ncurses                   6.5                  h2d0b736_3    conda-forge
ntlink                    1.3.11          py312h7896c42_1    bioconda
numpy                     1.24.4           py38h59b608b_0    conda-forge
openmpi                   4.1.6              hc5af2df_101    conda-forge
openssl                   1.1.1w               hd590300_0    conda-forge
pcre2                     10.43                hcad00b1_0    conda-forge
perl                      5.32.1          7_hd590300_perl5    conda-forge
pigz                      2.8                  h2797004_0    conda-forge
pip                       24.3.1             pyh8b19718_0    conda-forge
pixman                    0.44.2               h29eaf8c_0    conda-forge
pthread-stubs             0.4               hb9d3cd8_1002    conda-forge
pybedtools                0.10.0           py38hd638cd3_2    bioconda
pycairo                   1.25.0           py38h1a1917b_1    conda-forge
pysam                     0.9.1           py38hd1a2d5f_10    bioconda
python                    3.8.15          h257c98d_0_cpython    conda-forge
python-igraph             0.8.3            py38h46e8ee3_3    conda-forge
python_abi                3.8                      5_cp38    conda-forge
readline                  8.2                  h8c095d6_2    conda-forge
samtools                  1.3.1                h80b0bb3_7    bioconda
setuptools                75.3.0             pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sysroot_linux-64          2.17                h0157908_18    conda-forge
tar                       1.34                 hb2e2bae_1    conda-forge
texttable                 1.7.0              pyhd8ed1ab_0    conda-forge
tigmint                   1.2.1                      py_0    bioconda
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2025a                h78e105d_0    conda-forge
util-linux                2.39.4           py38heb36ba7_0    conda-forge
wget                      1.20.3               ha56f1ee_1    conda-forge
wheel                     0.45.1             pyhd8ed1ab_0    conda-forge
xorg-libice               1.1.2                hb9d3cd8_0    conda-forge
xorg-libsm                1.2.6                he73a12e_0    conda-forge
xorg-libx11               1.8.12               h4f16b4b_0    conda-forge
xorg-libxau               1.0.12               hb9d3cd8_0    conda-forge
xorg-libxdmcp             1.1.5                hb9d3cd8_0    conda-forge
xorg-libxext              1.3.6                hb9d3cd8_0    conda-forge
xorg-libxrender           0.9.12               hb9d3cd8_0    conda-forge
xz                        5.6.4                hbcc6ac9_0    conda-forge
xz-gpl-tools              5.6.4                hbcc6ac9_0    conda-forge
xz-tools                  5.6.4                hb9d3cd8_0    conda-forge
zip                       3.0                  hd590300_3    conda-forge
zlib                      1.2.13               h4ab18f5_6    conda-forge
```

It appears to be issue in package versions management within `conda`. May be adding suggestion to check versions of some repos to Readme help to address the issue further?

Best regards
Asan
