### ISSUE TITLE
ONT read lengths mostly under 10 kb

### ISSUE THREAD

**Issue by 000generic** [bcgsc/goldrush#117]
Hi! 

I have an ONT data set for a likely human-sized repeat-rich heterozygous genome with around 40x coverage. We tried various DNA extraction methods but a beta PromethION system in 2018 kept clogging - so we ended up shearing the DNA to 20 kb and then sequenced to get around clogging. Average read length was around 12 kb and many lengths go down to the 1 kb cutoff for the read set. 

I assembled the reads using NextDenovo with a minimum read length of 1 kb - so all available read lengths - and it assembled to 1300 contigs with a 2.3 mB n50 and 89% BUSCO Metazoa - but 1.5 Gb assembled, so less than expected but we don't have any actual measurements or estimates yet. Overall, reasonably good - though it took 5 weeks to finish and guidance from the developers as it was much slower than expected. 

I next assembled with Goldrush:

`goldrush run reads=all-ont-reads G=3e9 t=60 m=1000 
`

and it finished in a day but assembled relatively poor: 3500 contigs with a 0.3 mB n50.

I'm wondering if like for NextDenovo, it is necessary to adjust goldrush parameters for the shorter ONT read lengths. Or in general, are there parameters you might recommend in this situation or in general for testing?

I don't have a measurement or estimate of genome size for the species yet - guessing it is around human sized based on related species.

My machines are either 45 CPU and 1 Tb RAM or 60 CPU and 500 Gb RAM.

Thank you very much :)
Eric

**Comment by jwcodee** [comment]
Hi, Eric. Is the data from 2018 too or just the machine? I'm wondering if the chemistry is modern,

I would first recommend trying :
`goldrush run reads=all-ont-reads G=3e9 t=60 m=10000` if the average read length is 12,000. 
GoldRush works better with longer reads and does not need all available reads.

If the data is old, you may have to change the `P` parameter to 10.

I should note that this is quite exploratory as we have not tried assembling repeat-rich datasets with low read length. High read lengths aids GoldRush in distinguishing repeats to an extent and scaffolding.

Regards,
Johnathan
