### ISSUE TITLE
goldrush for generating UMI consensus?

### ISSUE THREAD

**Issue by sagnikbanerjee15** [bcgsc/goldrush#118]
Hello,

Would it be prudent to use goldrush to generate UMI consensus sequences from PacBio, assuming we can estimate the length of the consensus sequence?

Thank you

**Comment by jwcodee** [comment]
I want to clarify. The input reads would be all the sequences with the same UMI (derived from the same template molecule)? Assuming you can estimate the template molecule length, GoldRush could work for your purpose. How long are these molecules typically?

**Comment by sagnikbanerjee15** [comment]
Hello,

Thanks for the quick reply. Yes, all the reads are from the same template molecule bearing the same UMI sequence. This library is prepared from a single target gene. The reason why we decided to sequence using long reads is to capture SNPs that have been introduced. Even if we do not do a targeted sequencing we should be good. For this library, the sequence should be around 570-600 bp. 

Thank you.

**Comment by jwcodee** [comment]
In which case you will have to change some GoldRush settings as it has not been tested on molecules that short before.  Is the gene 600-700bp or the pacbio reads?

**Comment by sagnikbanerjee15** [comment]
The gene is around 525 nucl long with a 90 bp long barcode.

**Comment by jwcodee** [comment]
In which case, I would recommend just running GoldPolish by selecting a high quality base read (i.e. golden path read) to polish.
