### ISSUE TITLE
bc unknown command

### ISSUE THREAD

**Issue by thdurand4** [bcgsc/goldrush#128]
Hello i am trying to use goldrush assembler on my diploid genome of mosquito and when i launch the pipeline every works fine but for one step when it launch : goldrush-edit-ntedit script i have an error because he doesn"t know the bc commande i think its at this line : 

size_diff=$(echo "scale=4; $output_size / $input_size" | bc). 

But it is very strange because when i am on my terminal i can use bc command but when i launch the pipeline, after he fails i can't use anymore bc command. 

I have installed it well with conda/mamba. 

Thanks for your answers. 
Théo

**Comment by lcoombe** [comment]
Hi Théo,

That is quite strange! What version of goldrush are you using, and what conda build? (You can find that with `conda list`)
If you run `which bc`, what path do you see?

Also, could you share your full command and standard out/error with us?

Thank you for your interest in GoldRush!
Lauren

**Comment by thdurand4** [comment]
Hello 

When i use conda list command i see this : 

```goldrush  1.0.3  py38h2494328_1  bioconda```

which bc : /usr/bin/bc

**Comment by thdurand4** [comment]
Ohhhhh i think i got it,

I use a cluster to launch Goldrush and i just saw when i am on a node bc command doesn't exist but when i am on master its work that strange ! 

I will try to fix it.
