### ISSUE TITLE
Error while running HiFi reads whose mean length is 10k bp

### ISSUE THREAD

**Issue by Oieswarya** [bcgsc/goldrush#135]
Hello I am trying to run GoldRush with my simulated HiFi reads.

This is the command I am using to run:
goldrush run reads=DB G=119e6 track_time=1 m=10000

This is the error I am getting:
Using preset spaced seed
with:
	span: 22
	weight: 16
Calculating 5 silver path(s)
Using:
	tile length: 1000
	block size: 10
	seed patterns: 3
	threshold: 10
	base seed pattern: 1011011110110111101101
	minimum unassigned tiles: 5
	maximum assigned tiles: 1
	expected hash space: 357000000
	minimum average phred quality score: 15
	maximum average phred delta between first and second half of read: 5
	occupancy: 0.1
	jobs: 48
allocating bit vector
m_filterSize: 3388366144
finished allocating bit vector
in 0.0912
opening: DB.fq
inserting bit vector
num_passed_reads: 123718
num_reads: 123781
num_reads - num_passed_reads: 63
num_reads - num_passed_reads / num_reads: 0.0000
num_reads_skipped_by_phred: 0
num_reads_skipped_by_delta: 0
num_reads_skipped_by_length: 63
Total reads skipped: 63
finished inserting bit vector
in 70.2657
assigning tiles
/opt/conda/conda-bld/goldrush_1712165179978/_build_env/x86_64-conda-linux-gnu/include/c++/12.3.0/bits/stl_vector.h:1142: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](size_type) const [with _Tp = std::vector<long unsigned int>; _Alloc = std::allocator<std::vector<long unsigned int> >; const_reference = const std::vector<long unsigned int>&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
/opt/conda/conda-bld/goldrush_1712165179978/_build_env/x86_64-conda-linux-gnu/include/c++/12.3.0/bits/stl_vector.h:1142: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](size_type) const [with _Tp = std::vector<long unsigned int>; _Alloc = std::allocator<std::vector<long unsigned int> >; const_reference = const std::vector<long unsigned int>&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
make[1]: *** [/home/.conda/envs/goldrush_env/bin/goldrush.make:251: goldrush_asm_silver_path_5.fq] Error 6
make: *** [/home/.conda/envs/goldrush_env/bin/goldrush.make:203: run] Error 2

Is there any other parameter that I need to change for running GoldRush with HiFi reads?

**Comment by jwcodee** [comment]
Hello,

Thank you for your interest in using GoldRush.

GoldRush has been tested on HiFi reads with an N50 read length of 20kb. There may be some undefined behaviors when the read lengths are 10kb long. Can I first ask you to run the demo script located at https://github.com/bcgsc/goldrush/tree/main/tests to test your installation of GoldRush?

If that succeeds, I'd like you to try adding `--dry-run` to your command. There should be a command in the output to your terminal that looks like `goldrush run-in-dir ...` . Add `--dry-run` to that, and you should have another list of commands. Finally, I'd like you to run the first goldrush-path command with `--debug` and copy and paste the last few lines of the error so we can understand what is breaking and isolate the issue.

In the meantime, we will simulate some 10kb reads and try to address the issue on our end.

**Comment by Oieswarya** [comment]
Hello,

Thank you for your prompt response.
I have run your test script and it is running.

I am not exactly understanding how to run the --dry-run. Do you want me to use --dry-run instead of run?

I have run the goldrush-path --debug with my data.
This is the command I used:
goldrush goldrush-path reads=DB G=119e6 track_time=1 m=10000 --debug

And this is the log file for that:
Using preset spaced seed
with:
	span: 22
	weight: 16
Calculating 5 silver path(s)
Using:
	tile length: 1000
	block size: 10
	seed patterns: 3
	threshold: 10
	base seed pattern: 1011011110110111101101
	minimum unassigned tiles: 5
	maximum assigned tiles: 1
	expected hash space: 357000000
	minimum average phred quality score: 15
	maximum average phred delta between first and second half of read: 5
	occupancy: 0.1
	jobs: 48
allocating bit vector
m_filterSize: 3388366144
finished allocating bit vector
in 0.0889
opening: DB.fq
inserting bit vector
num_passed_reads: 64224
num_reads: 123781
num_reads - num_passed_reads: 59557
num_reads - num_passed_reads / num_reads: 0.0000
num_reads_skipped_by_phred: 0
num_reads_skipped_by_delta: 0
num_reads_skipped_by_length: 59557
Total reads skipped: 59557
finished inserting bit vector
in 34.5325
assigning tiles
/opt/conda/conda-bld/goldrush_1712165179978/_build_env/x86_64-conda-linux-gnu/include/c++/12.3.0/bits/stl_vector.h:1142: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](size_type) const [with _Tp = std::vector<long unsigned int>; _Alloc = std::allocator<std::vector<long unsigned int> >; const_reference = const std::vector<long unsigned int>&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
/opt/conda/conda-bld/goldrush_1712165179978/_build_env/x86_64-conda-linux-gnu/include/c++/12.3.0/bits/stl_vector.h:1142: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](size_type) const [with _Tp = std::vector<long unsigned int>; _Alloc = std::allocator<std::vector<long unsigned int> >; const_reference = const std::vector<long unsigned int>&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
make: *** [/home/.conda/envs/goldrush_env/bin/goldrush.make:251: goldrush_asm_silver_path_5.fq] Error 6

**Comment by Oieswarya** [comment]
Thank you for the clarification.

I tried running it and this is the .o log file:

`mkdir -p goldrush_intermediate_files
cd goldrush_intermediate_files && ln -sf ../DB.fq && goldrush run-in-dir reads=DB G=119e6 t=48 z=1000 track_time=1 k=22 w=16 tile=1000 b=10 u=5 a=1 o=0.1 x=10 h=3 s=1011011110110111101101 m=10000 M=5 r=0.9 P=15 d=5 span=2 dist=500 k_ntLink=40 w_ntLink=250 rounds=5 polisher=goldpolish polisher_mapper=minimap2 shared_mem=/dev/shm
ln -sf goldrush_intermediate_files/goldrush_asm_golden_path.fa
ln -sf goldrush_intermediate_files/goldrush_asm_golden_path.goldpolish-polished.fa
ln -sf goldrush_intermediate_files/goldrush_asm_golden_path.goldpolish-polished.span2.dist500.tigmint.fa
ln -sf goldrush_intermediate_files/goldrush_asm_golden_path.goldpolish-polished.span2.dist500.tigmint.fa.k40.w250.ntLink-5rounds.fa
echo "You can find intermediate files and the outputs for each GoldRush stage within the goldrush_intermediate_files subdirectory."
echo "A soft link to your final assembly is available at: goldrush_asm_golden_path.goldpolish-polished.span2.dist500.tigmint.fa.k40.w250.ntLink-5rounds.fa"'

But no directory or anything is getting created.

**Comment by jwcodee** [comment]
My apologies. It has been quite hectic recently so I have not been able to respond promptly. 

Right, so a `--dry-run` doesn't run anything. It is there to allow you to examine the commands the makefile would run so you could inspect if parameters are being passed properly for example.

```goldrush run-in-dir reads=DB G=119e6 t=48 z=1000 track_time=1 k=22 w=16 tile=1000 b=10 u=5 a=1 o=0.1 x=10 h=3 s=1011011110110111101101 m=10000 M=5 r=0.9 P=15 d=5 span=2 dist=500 k_ntLink=40 w_ntLink=250 rounds=5 polisher=goldpolish polisher_mapper=minimap2 shared_mem=/dev/shm```

So the above goldrush make command will initiate the assembly process in the directory that it is supposed to create. 
Can you run that with `--dry-run` like below?

```goldrush run-in-dir reads=DB G=119e6 t=48 z=1000 track_time=1 k=22 w=16 tile=1000 b=10 u=5 a=1 o=0.1 x=10 h=3 s=1011011110110111101101 m=10000 M=5 r=0.9 P=15 d=5 span=2 dist=500 k_ntLink=40 w_ntLink=250 rounds=5 polisher=goldpolish polisher_mapper=minimap2 shared_mem=/dev/shm --dry-run```


That will give you another list of commands, Run the first `goldrush-path` with the `--debug` option.

**Comment by jwcodee** [comment]
Hello, we've investigated and found that GoldRush will run successfully with reads that are only 10kbp in length. 


We, however, found an issue where if your reads are non atcg characters, we might experience errors like the one you are seeing. Can you confirm your reads only contain atcg and no other chars?

**Comment by Oieswarya** [comment]
Thank you so much for clarifying. The long reads file indeed had N's. I have removed it and now it is running.
