### ISSUE TITLE
Can goldrush be used to assemble hifi-reads?

### ISSUE THREAD

**Issue by xiekunwhy** [bcgsc/goldrush#78]
Hi,

Can I use [goldrush](https://github.com/bcgsc/goldrush) to assemble hifi-reads?

Best,
Kun

**Comment by jowong4** [comment]
GoldRush works with Hi-Fi reads but you may have to adjust the min read length parameter `m`. You should be able to set it to whatever library size the reads are sequenced with.

**Comment by xiekunwhy** [comment]
Ok, I will try it.
