### ISSUE TITLE
Filename should not contain .

### ISSUE THREAD

**Issue by hjjansen** [bcgsc/goldrush#80]
When trying to run Goldrush v1.0.1 installed through conda it failed to start. 
Command:
`goldrush run reads=filename.with.period G=6e8 t=54`
Relevant part of output:
```
goldrush-path  -k 22 -w 16 -t 1000 -u 5 -a 1 -o 0.1 -p w16_x10_silver_path -i   -h 3 -j 54 -x10 -P 15 -d 5 -s 1011011110110111101101 -g 6e8 -b 10 -r 0.9 --silver_path -M 5 -m 20000

opening: -h
inserting bit vector
cat: invalid option -- 'h'
Try 'cat --help' for more information.
[2022-10-31 11:49:15][WARNING] -h is empty.
Gold Path requires fastq format
[2022-10-31 11:49:15][ERROR] A helper process has finished unsuccessfully:
PID: 33206
Outcome: exited with status 1
```
Clearly `-i` doesn't get populated from the reads option.
Changing the run command to 
`goldrush run reads=filename-without-period G=6e8 t=54`
let the pipeline starts as intended.
It could be a good idea to at least mention this in the documentation.

**Comment by jowong4** [comment]
Hi. Can you show me the exact command as well as the name of your input fastq reads? I did a toy trial run and GoldRush captured the input.
```
(goldrush_publish) [jowong@hpce704 file_test]$ ls
filename.with.period.fq
(goldrush_publish) [jowong@hpce704 file_test]$ goldrush run reads=filename.with.period G=6e8 t=54 --dry-run
goldrush-path  -k 22 -w 16 -t 1000 -u 5 -a 1 -o 0.1 -p w16_x10_silver_path -i filename.with.period.fq  -h 3 -j 54 -x10 -P 15 -d 5 -s 1011011110110111101101 -g 6e8 -b 10 -r 0.9 --silver_path -M 5 -m 20000
cat w16_x10_silver_path_*.fq > w16_x10_silver_path_all.fq
```

**Comment by osilander** [comment]
I'm getting the same error even when removing . from the filename and changing from .fastq to .fq (goldrush v1.0.1 installed via mamba from the bioconda channel)

```
goldrush run reads=reads-simplex-filter.fq G=1e9 t=44
```
gives

```
goldrush-path  -k 22 -w 16 -t 1000 -u 5 -a 1 -o 0.1 -p w16_x10_silver_path -i   -h 3 -j 44 -x10 -P 15 -d 5 -s 1011011110110111101101 -g 1e9 -b 10 -r 0.9 --silver_path -M 5 -m 20000
Using preset spaced seed...
```
A dry run:
```
goldrush run reads=reads-simplex-filter.fq G=1e9 t=44 --dry-run
```
gives
```
goldrush-path  -k 22 -w 16 -t 1000 -u 5 -a 1 -o 0.1 -p w16_x10_silver_path -i   -h 3 -j 44 -x10 -P 15 -d 5 -s 1011011110110111101101 -g 1e9 -b 10 -r 0.9 --silver_path -M 5 -m 20000
cat w16_x10_silver_path_*.fq > w16_x10_silver_path_all.fq
goldrush-path  -k 22 -w 16 -t 1000 -u 5 -a 1 -o 0.1 -p w16_x10_golden_path -i w16_x10_silver_path_all.fq -h 3 -j 44 -P 15 -d 5 -x10 -s 1011011110110111101101 -g 1e9 -b 10  -m 0
echo "Done GoldRush-Path! Golden path can be found in: w16_x10_golden_path.fa"
```
I'm confused why the second line of the dry run says `-i w16_x10_silver_path_all.fq`

**Comment by jowong4** [comment]
Hi. you need to remove the `.fq` from the command. If your input filename is named `reads.fq` the goldrush input parameter would take in `reads`.

Regarding your second question. `goldrush-path` is ran twice. The first time, it generates silver paths which are, by default, a ~0.9X representation of the genome. Then we combine these silver paths to generate the `w16_x10_silver_path_all.fq`, a efficient subsample of the original dataset, and what you see in the second command. The file is then used as input to generate the golden path

**Comment by hjjansen** [comment]
> Hi. Can you show me the exact command as well as the name of your input fastq reads? I did a trial run and GoldRush captured the input.
> 
> ```
> (goldrush_publish) [jowong@hpce704 file_test]$ ls
> filename.with.period.fq
> (goldrush_publish) [jowong@hpce704 file_test]$ goldrush run reads=filename.with.period G=6e8 t=54 --dry-run
> goldrush-path  -k 22 -w 16 -t 1000 -u 5 -a 1 -o 0.1 -p w16_x10_silver_path -i filename.with.period.fq  -h 3 -j 54 -x10 -P 15 -d 5 -s 1011011110110111101101 -g 6e8 -b 10 -r 0.9 --silver_path -M 5 -m 20000
> cat w16_x10_silver_path_*.fq > w16_x10_silver_path_all.fq
> ```

My command was:
`goldrush run reads=FG2140_alldata_guppy_v6.3.2sup_pass_trimmed G=6e8 t=54` 
The filename is `FG2140_alldata_guppy_v6.3.2sup_pass_trimmed.fq`
This:
`goldrush run reads=Q18_FG2140_alldata_guppy_v6-3-2sup_pass_trimmed G=6e8 t=54`
works.
Our cluster runs on CentOS Linux release 7.6.1810.
`uname -r` gives `3.10.0-957.10.1.el7.x86_64`
If you need more information please let me know.

**Comment by jowong4** [comment]
> My command was: `goldrush run reads=FG2140_alldata_guppy_v6.3.2sup_pass_trimmed G=6e8 t=54` 
The filename is `FG2140_alldata_guppy_v6.3.2sup_pass_trimmed.fq` 

I have checked that name and it works with a softlink with that name.

> This: `goldrush run reads=Q18_FG2140_alldata_guppy_v6-3-2sup_pass_trimmed G=6e8 t=54` works. 
 
Is the file `FG2140_alldata_guppy_v6.3.2sup_pass_trimmed.fq` a softlink of `Q18_FG2140_alldata_guppy_v6-3-2sup_pass_trimmed`? If the soft link is broken, it can also lead to an empty input to the input parameter.

**Comment by hjjansen** [comment]
No this is not soft linked, file is in the same directory.

**Comment by lcoombe** [comment]
Hi @hjjansen,

I'm try to reproduce your error on our end, but without success - running on a CentOS machine, I get: 
```
(test_goldrush) [lcoombe@hpce705 tmp]$ ls
FG2140_alldata_guppy_v6.3.2sup_pass_trimmed.fq
(test_goldrush) [lcoombe@hpce705 tmp]$ goldrush run reads=FG2140_alldata_guppy_v6.3.2sup_pass_trimmed G=6e8 t=54 -n
goldrush-path  -k 22 -w 16 -t 1000 -u 5 -a 1 -o 0.1 -p w16_x10_silver_path -i FG2140_alldata_guppy_v6.3.2sup_pass_trimmed.fq  -h 3 -j 54 -x10 -P 15 -d 5 -s 1011011110110111101101 -g 6e8 -b 10 -r 0.9 --silver_path -M 5 -m 20000
```
So the file is found fine with the periods.

If it isn't too much trouble, as another sanity check, would you mind executing again (and sharing the output):
```
ls -lah FG2140_alldata_guppy_v6.3.2sup_pass_trimmed.fq
head -n1  FG2140_alldata_guppy_v6.3.2sup_pass_trimmed.fq
goldrush run reads=FG2140_alldata_guppy_v6.3.2sup_pass_trimmed G=6e8 t=54 -n
```

Thank you for your interest in GoldRush!

**Comment by osilander** [comment]
Apologies and thanks. Could you maybe clarify in the docs

"For example, to run the default pipeline on reads 'reads.fq' with a genome size of gsize:
```
goldrush run reads=reads G=gsize
```
where the `reads` argument **does not have** the `fq` file extension."

(bold probably not necessary). This wasn't obvious to me, but this was probably partially out of habit of using tab-complete or that other programs frequently require the full name.

Looking forward to seeing my results!

**Comment by lcoombe** [comment]
Thanks for the suggestion, @osilander! 
We have added more explicit directions about the `reads` variable in the README and help page. We also added logic to the `goldrush` makefile that should catch the cases where the `reads` variable isn't set correctly (thus the underlying file isn't found) and print a more helpful error message (both in #83 )
