### ISSUE TITLE
tmpdir/shared_dir pass through from parent goldrush?

### ISSUE THREAD

**Issue by nextgenusfs** [bcgsc/goldrush#92]
I'm running into an issue where I can run the conda installed`goldrush` pipeline when in interactive mode without issue.  However, when I launch on our AWS/HPC equivlement it fails with "device out of memory" error -- My current hypothesis this is due to `goldrush-edit` -m option which defaults to `/dev/shm` -- this doesn't exist on our job system because we don't have swap.  But it doesn't seem like I can pass a tmpdir/shared location through the parent `goldrush` script?

My work around was to edit the `goldrush-edit` python script to default to writing args.shared_mem to `/tmp/goldrush-{uuid.uuid4()}`

**Comment by lcoombe** [comment]
Hi @nextgenusfs,

Thanks for the report! I added a parameter `shared_mem` to the `goldrush` file in #93 - So now that can be used from the parent `goldrush` script itself to specify the shared memory location. The update is in main branch right now, and will be included in the next GoldRush release (so will be reflected in the conda installation at that time).

Thanks for your interest in GoldRush!
Lauren
